version: "3"
services: 
    hub: 
        image: selenium/hub:latest
        ports:
            - "4444:4444"
    chrome:
        image: selenium/node-chrome:beta
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    firefox:
        image: selenium/node-firefox:beta
        shm_size: '1gb'
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
    search-module:
        image: 8049376624/selenium-docker
        depends_on:
            - chrome
            - firefox
        environment:
            - HUB_HOST=hub
            - BROWSER=chrome
            - MODULE=testng.xml
        volumes:
            - ./output/result:/Project/cucumberFW/target
        